### PR TITLE
Lazily evaluate relationship objects only when included

### PR DESCRIPTION
**Pull request by mwpastore**
My clumsy attempt at a fix for #29

### CODE REVIEW

**Comment by mwpastore** [comment]
Passing an enumerable Sequel dataset to JSONAPI::Serializers: 1400ms, 1084 queries
Passing an enumerable Sequel resultset (i.e. dataset`.all`) to JSONAPI::Serializers: 750ms, 580 queries
^^ with this fix: 460ms, 300 queries
^^ with Sequel eager loading: 130ms, 3 queries

Not bad for a day's work!

**Comment by mwpastore** [comment]
@fotinakis Any thoughts on this? There are a few different ways to implement the changes and I'm happy to make as many attempts as it takes to make you happy. :smile: Let me know. Thank you.

**Comment by fotinakis** [comment]
Hey @mwpastore, this looks pretty nice. I'm going to test this against an application I have now and let you know.

**Comment by fotinakis** [comment]
LGTM :+1: Thanks for doing this, things look like they are backwards-compatible. I will release a new gem after merging.

**Comment by fotinakis** [comment]
I've pushed v0.3.1 which includes this change.

**Comment by mwpastore** [comment]
:+1: Thanks Mike!

**Pull request merged**
