### PR TITLE
Use serializer objects including objects in stead of objects itself to get more stable dependent serializer lookup behavior

### PR DESCRIPTION
**Pull request by bterkuile**
Hi Mike,

I am looking of a good JSON API library in Ruby, and your gem looks really promising. While testing it there were some problems with serializer lookups and namespaces, even when provided through the options in the has_many specification. Passing around serializer objects in stead of the objects itself solves most of these.

This pull request also provides a more lean solution in passing through the include_relationships parameters and probably speeds up the generation.

The specs are really nice enabling me to easily make these changes!!

Maybe in the future passing around a 'global' context to prevent the double recursive run for adding includes might improve speed even more, but it looks like a start for that is already present in the code.

Controlling the information of the includes is part of my followup investigation so have no conclusive thing about that now.

Thanks for the nice gem!

### CODE REVIEW

**Comment by fotinakis** [comment]
Wow, this is a lot of work, thanks @bterkuile! And thank you for adding new tests for the new behaviors. This helps me get closer to the v2.0 interface I've been thinking about.

Since the public interface hasn't changed with this I think it's pretty safe, but I'd like to do a more in-depth review and test it with my own application to make sure nothing changes. I'll try to get to that next week.

**Comment by fotinakis** [comment]
I've spent a little while working on this PR and cleaning it up to be more consistent with the rest of the codebase. These changes are in https://github.com/fotinakis/jsonapi-serializers/commit/6f3c4ca594ed1324a9bd052de3a1caaeb516ae83 ... I also removed some Rails-specific dependencies (deep_stringify_keys) which were untested, protected methods that should not be public, etc. There are some things remaining that I'm not excited about, for example—there are now 3 different places that handling parsing and normalizing include paths, including the original parse_relationship_paths method...this duplication is unfortunate.

Even though the tests pass, I'm not totally convinced that this doesn't break certain behaviors. I'd like to do more testing before merging, and need to think about if we really should do this.

@bterkuile -- can you provide me a simple example of "some problems with serializer lookups and namespaces"? I want to make sure I understand exactly what you're solving.

**Comment by bterkuile** [comment]
An example where the current master serializer lookup will fail:
```ruby
class CommentSerializer
end

class MyNamespace::PostSerializer
  include ...
  has_many :comments, serializer: MyNamespace::CommentSerializer
end

class MyNamespace::CommentSerializer
end
```

The code in the current master:
```ruby
related_object_serializer = JSONAPI::Serializer.find_serializer(object)
```
will resolve the top level `CommentSerializer` in stead of the `MyNamespace::Serializer`, even while the namespaced version is explicitly given as argument. The latest pull request uses serializers as main objects having the association options included solving this issue.

And since commits on this repo are automatically added to the pull request here the situation the ActiveSupport::Concern implementation solves where the current implementation fails:

```ruby
class MyUserBaseSerializer
  extend ActiveSupport::Concern
  include JSONAPI::Serializer
  included do
    attribute :created_at
  end
end

class MyUserSerializer
  include MyUserBaseSerialzier
end
```

Or shortly said, creating your own custom serializer, based on the JSONAPI::Serializer with some custom application logic.

**Comment by bterkuile** [comment]
I see that the later more experimental pushes are also taken into merge request. This  makes it no longer a valid merge request, therefore closing it. There are still some issues for serializer lookup on IdObjects that for me are no problem since I explicitly specify all the serializers for all the relationships. The performance issues however are solved in this fork. My main focus will be to optimize first for a solid rails Ember integration and maybe generalize more afterwards.

**Pull request closed without merging**
