### PR TITLE
Include intermediate resources on compound documents

### PR DESCRIPTION
**Pull request by jcarlos**
Please see https://github.com/fotinakis/jsonapi-serializers/issues/49

### CODE REVIEW

**Comment by fotinakis** [comment]
Looks good, except for the big blocks of unformatted hashes. :) See the current style and way that tests are structured in the file, it should be pretty easy to update near comment `Only the author is included:` to include other objects (something like  `Intermediates are included: long-comments, long-comments.post, and long-comments.post.author`). If you could update the comments as well, that would be great.

**Comment by jcarlos** [comment]
No worries @fotinakis , I'll do the updates :)

Did you mean I should just format the hashes or to remove the big hashes and replace them with something like the code below?
 ```ruby
expected_data = {
        'data' => serialize_primary(post, {serializer: MyApp::PostSerializer}),
        'included' => [
          serialize_primary(post.long_comments.first, {serializer: MyApp::LongCommentSerializer}),
          serialize_primary(post.long_comments.last, {serializer: MyApp::LongCommentSerializer}),   
          serialize_primary(post, { serializer: MyApp::PostSerializer }),
          serialize_primary(post.author, {serializer: MyAppOtherNamespace::UserSerializer})
        ],
      }
```

I have tried this option first and then I replaced it with the direct big hash because ```expected_data``` was missing the ```"data"``` part inside the relationship of each include, ex:

```ruby
{
  "relationships"=> {
    "user"=> {
      "links"=> {
        "self"=>"/long-comments/2/relationships/user", 
         "related"=>"/long-comments/2/user"
      },
      "data"=> { # this data bit was missing for each included resource
        "type"=>"users", 
        "id"=>"2"
      }
    }
  }
}  
```

Maybe there is some special option that would include this ```"data"``` bit in there when using ```serialize_primary``` but I couldn't find it.

**Comment by jcarlos** [comment]
By the way, I have already included the comment you asked, formatted the hash and squashed my commits in case that was the only thing missing :)

**Comment by fotinakis** [comment]
Sorry I meant getting it to use the `serialize_primary` method like the rest of the tests, not formatting the hash. The reasoning here is to to tightly control what the tests expect and make sure we know exactly what the format is supposed to be.

The `data` issue you hit was correct, because were now including all intermediates along the way, each included object needs to have `data` to provide full linkage. You can get `serialize_primary` to include data like this (from another test):

```ruby
      serialize_primary(post, {
        serializer: MyApp::PostSerializer,
        include_linkages: ['author'],
      })
```

**Comment by jcarlos** [comment]
Got it, thanks for letting me know about the include_linkages. I have updated the specs accordingly, please have a look at the updated pull request @fotinakis

**Comment by fotinakis** [comment]
This looks great! :+1:

I'll merge this tomorrow, just need to think through the correct way to notate the change and I want to test it with my own app. I think this is relatively safe because 1) it brings it into compatibility with the JSON:API spec, and 2) it's just adding more data to compound documents, not removing anything or changing a format, so I believe this is backwards compatible and we can classify it a "bugfix".

**Comment by fotinakis** [comment]
Released in gem v0.6.1, thanks for your contribution.

**Pull request merged**
